[package]
name = "openapi_codegen"
description = "Generate well-typed code from an OpenAPI spec"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [
    "Charles Hall <charles@computer.surgery>",
]
