name: "CI"

on:
  push:
  pull_request:

env:
  # Make `tput` and other commands output color
  COLUMNS: "80"
  TERM: "ansi"
  CARGO_TERM_COLOR: "always"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Nix (this comes with (at least?) flakes and nix-command enabled)
      - uses: cachix/install-nix-action@v17
        with:
          # Unstable is fine because we only need `direnv` and `nix-direnv` from
          # it. Everything else comes from the flake.
          nix_path: nixpkgs=channel:nixpkgs-unstable

          # Add the `nix-community` cachix to speed up CI since we use `fenix`
          extra_nix_config: |
            substituters = https://nix-community.cachix.org https://cache.nixos.org/
            trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      # Configure `nix-direnv`
      - run: "mkdir -p $HOME/.config/nixpkgs"
      - run: "echo '[(self: super: { nix-direnv = super.nix-direnv.override { enableFlakes = true; }; })]' > $HOME/.config/nixpkgs/overlays.nix"
      - run: "echo 'source $HOME/.nix-profile/share/nix-direnv/direnvrc' > $HOME/.direnvrc"

      # Install `direnv` and `nix-direnv`
      - run: "nix-env -f '<nixpkgs>' -i direnv -i nix-direnv"

      # Allow our `.envrc`
      - run: "direnv allow"

      # GitHub Actions ships with these for some reason. We need to remove them
      # because of this: https://github.com/rust-lang/cargo/issues/6507
      - run: "rm -rf $HOME/.cargo $HOME/.rustup"

      # Run the actual CI script
      - run: "direnv exec . ci"
